### ISSUE TITLE
feature request: []string to []interface{}

### ISSUE THREAD

**Issue by kylewolfe** [olekukonko/tablewriter#20]
Append([]string) -> Append([]interface{}) This allows much more fluid table writes.

Given:

``` go
foo := struct{
    Foo   string
    Fizz   int
    Buzz float32
}{
   Foo: "bar",
   Fizz: 123,
   Buzz: 3.14,
}
tw := tablewriter.NewWriter(os.Stdout)
tw.SetHeader([]string{"foo", "fizz", "buzz"})
```

this allows for

``` go
tw.Append([]interface{}{
  foo.Foo,
  foo.Fizz,
  foo.Buzz,
})
```

rather than

``` go
tw.Append([]string{}{
  foo.Foo,
  strconv.Itoa(foo.Fizz),
  strconv.FormatFloat(foo.Buzz, 'f', 2, 64),
})
```

This can be achieved easily by leveraging fmt.Sprint. This will cause an API break, however. All code utilizing tablewriter would require Append([]string{}) to be converted to Append([]interface{}{}).

I'll begin a branch with this change. If you do not want to break API, then I can a new method call AppendInterface or something of that nature.

**Comment by ldmberman** [comment]
Hi @kylewolfe,

I do not like your approach. Let's consider your example:

```
tw.Append([]interface{}{
  foo.Foo,
  foo.Fizz,
  foo.Buzz,
})
```

And how we would write the same with the current interface:

```
tw.Append([]string{}{
  foo.Foo,
  fmt.Sprint(foo.Fizz),
  fmt.Sprint(foo.Buzz),
})
```

Yes, the latter is a bit more verbose but it tells us exactly what is going on. Looking at the former I have no idea about how it works under the hood and as a result I need to either dig into the library code or conduct some debug in order to find out that it actually uses `fmt.Sprint`.

Also, your option damages type-safety what may lead to situations where a user sees this ugly `{}`s or `[]`s in a table.  This may be the case when there is some subtle logic that dynamically forms table data. The current way, on the other hand, is a fail-fast way - we will know immediately if some unwanted type of data gets passed into the function.

And one more point to consider - I believe the `fmt.Sprint`'s default for floats (16 (!) floating point numbers ) is not appropriate for most of the use-cases of displaying numbers.

I know, the issues I have described may be avoided even if your approach is taken but the main problem I see here is that it **encourages** buggy-prone code.

**Comment by kylewolfe** [comment]
My thoughts were that if there is an undesirable outcome (which I don't believe will be common), like the display of a float, then at that point the column can be cast into a string.

**Comment by ldmberman** [comment]
Well, I see but why let an undesirable outcome be casted into a string? In my opinion, an undesirable outcome should be known of as early as possible so that we could handle it appropriately.

**Comment by kylewolfe** [comment]
Keep in mind, you'd essentially be picking up the behaviour of the standard fmt package. This behaviour is acceptable for that package in order to allow for a less verbose API. People are usually already well versed with the fmt package and will understand the behaviour, so long as you have it documented on your readme.

If you do not feel comfortable with this, I can continue to wrap my calls to Append() with a iToString() call.

**Comment by ldmberman** [comment]
One of the goals of the `fmt` package is debug. Therefore lesser verbosity comes very handy.

Anyway, let's wait and see what @olekukonko would say.

**Comment by crackcomm** [comment]
Hello. I also made a small library for tables, which I don't use anymore in favor of this one.

[Row values](https://godoc.org/github.com/crackcomm/go-clitable#Table.AddRow) in there are interfaces:

```Go
func (t *Table) AddRow(row map[string]interface{})
```

I made this library in 2013. Now I think interface values for printing interfaces is a wrong approach and makes Table interface more like a black box - You don't know what it's gonna spit out.
I don't think a table row should contain anything else than a string.
In the end user pretty much always want's to choose a custom formats for floats and others. 

I was considering it to make string values but I'm not gonna do it because some people may have to make changes in their code or they are gonna have problems with versioning etc. but I included url to this library in description for new users.

**Comment by olekukonko** [comment]
Sorry for the late response  ...  based on the current usage of this `API break` might not be feasible but what do you guys think ?

**Comment by olekukonko** [comment]
Another way we can satisfy both parties is introduce `Push` for `interface` (or a better function name) while `Append` && `AppendBulk`  remains unchanged

**Comment by olekukonko** [comment]
@crackcomm thanks for adding the link and your contributions ... I also think everything should be string because makes it easy to count length with out having the boiler plate of type identification & conversion
