### ISSUE TITLE
The row formatter / column width computation should handle tabs gracefully

### ISSUE THREAD

**Issue by knz** [olekukonko/tablewriter#36]
so we're using tablewriter over here at CockroachDB (thanks for your work!) and we're trying to format our schema definition statements inside table cells. These contain only ASCII with newlines, spaces and... tabs.

Right now if the row data contains tab characters the tabs are printed-as is and cause misalignments.

The row formatter should either replace tabs with spaces or adjust the row width computation based on tabs (and tab positions). Ideally tabs should stay properly aligned across multiple rows; and thus the code should keep track of tab stops.

For now we're working around the issue on our side ( https://github.com/cockroachdb/cockroach/pull/7048 ) by replacing tabs by spaces, but this kills tab alignment across rows. Let us know when you plan to do something about it.

**Comment by olekukonko** [comment]
Hello knz, It nice to know `tablewriter` is used in `CockroachDB`,  interestingly have got my eyes on `CockroachDB` and i think its a wonderful project 

The major issues  is `DisplayWidth`  and `WrapString`  which does not properly account for the lenght of `tab (\t)` and returns `1` instead of  `4` or `8`

There are 2 possible solution 

1.  Convert `tabs` automatically to `4` or `8` spaces
2.  Properly account for `tabs` and give it a fix length of `4` or `8` (Which is a bit more tricky and additional overhead) 

I would look at this issues critically and look at the best possible ways to fix it ... Please note that suggestions and pull request are also welcome.

**Comment by knz** [comment]
We are now working around in CockroachDB by using `tabwriter` from golang. Perhaps this is an idea you can reuse too.
