### ISSUE TITLE
Feature request: coloured output

### ISSUE THREAD

**Issue by Epse** [olekukonko/tablewriter#37]
Having coloured output (probably optional) to give certain table elements a different colour, or headings in a different colour.
This would improve readability on some larger tables by quite a bit and might even be clearer, for example when you have a table with names and a simple yes/no column you could colour the names red or green.

Just a suggestion, as usual.

**Comment by olekukonko** [comment]
Good Idea .... I would look into it .. thanks. Please note that pull request is also welcome .... Regards

**Comment by eqot** [comment]
I could manage to get coloured output with ```github.com/fatih/color``` like this.

![colored-table](https://dl.dropboxusercontent.com/u/972960/Documents/nory/colored-table-in-go.png)

[Here](https://gist.github.com/eqot/0a1d10c9262563a67155b790ca9f2320) is a sample code.

A tricky thing is that ```SetAutoFormatHeaders(false)``` needs to be called, otherwise headers are broken.

**Comment by olekukonko** [comment]
This is a nice idea ... I think if there is a way to seamlessly make it work .... The fact that you can highlight each text is what makes it complex ... 

`SetAutoFormatHeaders` can easily be modify to identify and respect color options

**Comment by MrBlaTi** [comment]
@eqot 
I'm using fatih/color as well, but you gotta be careful with that. when coloring the contents of a cell, olekukonkos tablewriter will break up the lines and rearrange them as it think's it's best, stretching the ansi color escape sequences over multiple lines. it looks a little something like this then 
![errors](https://cloud.githubusercontent.com/assets/7404969/24246703/efed4350-0fc8-11e7-94b1-afa6c13578f1.png)
it would be great if @olekukonko could implement it natively, until then I#ll try and see what happens if I color each single word or even each single char

**Comment by mattn** [comment]
Closed by https://github.com/olekukonko/tablewriter/pull/50, https://github.com/olekukonko/tablewriter/pull/70
